# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "neustar-ws_get_data"
  s.version = "0.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Zachary Belzer"]
  s.date = "2013-10-22"
  s.description = "This gem wraps the SOAP interface for Neustar's\n    WS-GetData Services. It supports both interactive and batch queries"
  s.email = "zach@tmxcredit.com"
  s.extra_rdoc_files = [
    "LICENSE",
    "README.md"
  ]
  s.files = [
    ".rspec",
    ".ruby-gemset",
    ".ruby-version",
    "Gemfile",
    "LICENSE",
    "README.md",
    "Rakefile",
    "VERSION",
    "lib/neustar-ws_get_data.rb",
    "lib/neustar-ws_get_data/client.rb",
    "lib/neustar-ws_get_data/elements/phone_attributes.rb",
    "lib/neustar-ws_get_data/version.rb",
    "neustar-ws_get_data.gemspec",
    "spec/fixtures/fault.xml",
    "spec/fixtures/phone_attributes_success.xml",
    "spec/lib/neustar-ws_get_data/client_spec.rb",
    "spec/lib/neustar-ws_get_data/elements/phone_attributes_spec.rb",
    "spec/spec_helper.rb",
    "spec/support/savon.rb",
    "test.rb"
  ]
  s.homepage = ""
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "2.0.7"
  s.summary = "Ruby wrapper for Neustar's WS-GetData Services"

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<savon>, ["~> 2.2"])
      s.add_development_dependency(%q<rspec>, ["~> 2.14.0"])
      s.add_development_dependency(%q<yard>, ["~> 0.6.0"])
      s.add_development_dependency(%q<bundler>, [">= 0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.6.4"])
    else
      s.add_dependency(%q<savon>, ["~> 2.2"])
      s.add_dependency(%q<rspec>, ["~> 2.14.0"])
      s.add_dependency(%q<yard>, ["~> 0.6.0"])
      s.add_dependency(%q<bundler>, [">= 0"])
      s.add_dependency(%q<jeweler>, ["~> 1.6.4"])
    end
  else
    s.add_dependency(%q<savon>, ["~> 2.2"])
    s.add_dependency(%q<rspec>, ["~> 2.14.0"])
    s.add_dependency(%q<yard>, ["~> 0.6.0"])
    s.add_dependency(%q<bundler>, [">= 0"])
    s.add_dependency(%q<jeweler>, ["~> 1.6.4"])
  end
end

